### ISSUE TITLE
Can't install with the error on Mac.

### ISSUE THREAD

**Issue by msuzukiheroku** [heroku/heroku-slugs#14]
when install, following error was happened. What should I do to install ?

error An unexpected error occurred: "http://cli-npm.heroku.com/@oclif/config/-/config-1.6.33/61906143b30751d96dd29991c20c214bf4d9e4ff.tgz: Request failed \"404 Not Found\"".
Installing plugin heroku-slugs... !
Error: yarn add heroku-slugs@latest --non-interactive --mutex=file:/Users/XXXXXXXX/.local/share/heroku/yarn.lock --preferred-cache-folder=/Users/XXXXXXXX/Library/Caches/heroku/yarn --check-files --registry=https://registry.npmjs.org exited with code 1
    at ChildProcess.forked.on (~/.local/share/heroku/client/7.12.2/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

**Comment by jemminger** [comment]
Same issue here.  The 404'ed file seems to switch randomly.

```
$ heroku plugins:install heroku-slugs
error An unexpected error occurred: "http://cli-npm.heroku.com/lodash/-/lodash-4.17.10/1b7793cf7259ea38fb3661d4d38b3260af8ae4e7.tgz: Request failed \"404 Not Found\"".
Installing plugin heroku-slugs... !
Error: yarn add heroku-slugs@latest --non-interactive --mutex=file:/Users/jemminger/.local/share/heroku/yarn.lock --preferred-cache-folder=/Users/jemminger/Library/Caches/heroku/yarn --check-files --registry=https://registry.npmjs.org exited with code 1
    at ChildProcess.forked.on (~/.local/share/heroku/client/7.14.1/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)
 !    error installing plugin heroku-slugs

```

Furthermore, this error occurs when trying to install any heroku plugin, not just 'heroku-slugs'

**Comment by dmathieu** [comment]
Ping @heroku/cli

**Comment by RasPhilCo** [comment]
Remove the `yarn.lock` file which will cause the CLI to rebuild it: `rm ~/.local/share/heroku/yarn.lock`. It should update to use npm's registry.

**Comment by jemminger** [comment]
Thanks @RasPhilCo, that fixed it

**Comment by xsalefter** [comment]
Just additional info for people that might looking for other solution: For me, after deleting all of those yarn.lock file, I need to re-open my tab. Also, I need to execute `heroku plugins:install heroku-slugs` command from my home directory. So:

- `/other/than/home/dir~:$` `heroku plugins:install heroku-slugs` Error.
- `/home/me~:$` `heroku plugins:install heroku-slugs` Success.

Not sure what is actually causing the problem.
