### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by NickLiffen** [heroku/heroku-slugs#16]
Is there any plans to honour a proxy? If we build out the proxy support, would you merge it in? 😄 👋 We need to run this behind a proxy, and it isn't working :(

**Comment by dmathieu** [comment]
If there is indeed a lack of proxy support. It's something which should be handled within the broader CLI. Not this plugin.
I would recommend opening a support ticket so you can have a direct discussion with our CLI team.

**Comment by NickLiffen** [comment]
Hey, 👋 Thanks for your message. So by default, the proxy is honoured by the CLI, as you can see by this [proxy section](https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy). However, I don't think the plugins honour the proxy passed in by the standard CLI. Hence why I think each plugin needs its own proxy support, OR, somehow you are able to reference the plugin proxy? Just my thoughts based on what I can see.?

**Comment by dmathieu** [comment]
The plugins are using libraries and configuration provided by the main CLI. They definitely shouldn't all handle the proxy configuration, but inherit it from the main one. If that's not handled, it's an issue in the core cli, not in the plugin.

**Comment by NickLiffen** [comment]
Okay, thanks 👍I am going to open an issue on the main CLI repo then and reference this issue, can we leave this open for a little bit, I appreciate your quick responses 👍

**Comment by jgwhite** [comment]
Thanks for the report. I took a look into this and it turns out that because this plugin is a little bit older, it uses an older version of heroku-client too. The good news is, the older version of heroku-client has proxy support too, but uses slightly-different environment variables:

> If you'd like to make requests through an HTTP proxy, set the `HEROKU_HTTP_PROXY_HOST` environment variable with your proxy host, and `HEROKU_HTTP_PROXY_PORT` with the desired port (defaults to 8080). heroku-client will then make requests through this proxy instead of directly to api.heroku.com. 
>
> — [heroku-client README](https://github.com/heroku/node-heroku-client/blob/master/README.md#http-proxies)

**Comment by NickLiffen** [comment]
Thanks for the note, I will try and respond 👍
