### ISSUE TITLE
Document slugs:list in README

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-slugs#9]
The `slugs:list` command was added in #1, however it's not mentioned in the README.

I tried to use the heroku-cli-dev-center-generator tool to auto-generate a new README from the command's help text, however hit heroku/heroku-cli-dev-center-generator#4.

**Comment by mobilutz** [comment]
@edmorley There is not `heroku slugs:list` just `heroku slugs` and `heroku slugs:download`

```
❯ heroku --version
heroku/7.59.0 darwin-x64 node-v12.21.0

❯ heroku plugins
...
heroku-slugs 1.1.0

❯ heroku slugs:list -a APP
 ›   Warning: slugs:list is not a heroku command.
Did you mean apps:list? [y/n]: n
```
